# Generated by Django 4.1.7 on 2023-06-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0002_alter_commune_options_alter_profession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofdesc',
            name='cercle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.commune'),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='duree',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='nom_memb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='nom_prenom_president',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='num_refe',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='num_tf',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='numreo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='p_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='pdf_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.province'),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='tele',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
