# Generated by Django 4.1.7 on 2023-06-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0003_alter_proofdesc_cercle_alter_proofdesc_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofdesc',
            name='cercle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.commune'),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='duree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='nom_memb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='nom_prenom_president',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='num_refe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='num_tf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='numreo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='p_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.province'),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='tele',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
