# Generated by Django 4.1.7 on 2023-06-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0004_alter_proofdesc_cercle_alter_proofdesc_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.commune'),
        ),
    ]
