# Generated by Django 4.1.7 on 2023-06-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0005_alter_users_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.commune'),
        ),
        migrations.AlterField(
            model_name='users',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.province'),
        ),
    ]
