# Generated by Django 4.1.7 on 2023-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0008_alter_users_user_email_alter_users_user_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particulier',
            name='cin_pdf',
            field=models.FileField(null=True, upload_to='cin'),
        ),
    ]
