# Generated by Django 4.1.7 on 2023-06-08 19:04

import assisto.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0009_alter_particulier_cin_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particulier',
            name='cin_pdf',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d', validators=[assisto.validators.validate_file_extension]),
        ),
    ]
