# Generated by Django 4.1.7 on 2023-06-08 20:43

import assisto.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0010_alter_particulier_cin_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_pdf', models.FileField(null=True, upload_to='documents/%Y/%m/%d', validators=[assisto.validators.validate_file_extension])),
            ],
        ),
    ]
