# Generated by Django 4.1.7 on 2023-06-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0013_alter_phoneverification_phone_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneverification',
            old_name='phone_number',
            new_name='user_number',
        ),
    ]
