# Generated by Django 4.1.7 on 2023-06-11 20:51

import assisto.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0014_rename_phone_number_phoneverification_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pp',
            name='cin_pdf',
            field=models.FileField(null=True, upload_to='uploads', validators=[assisto.validators.validate_file_extension]),
        ),
    ]
