# Generated by Django 4.1.7 on 2023-06-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0016_alter_particulier_cin_pdf_alter_pp_cin_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='proof_abr',
        ),
    ]
