# Generated by Django 4.1.7 on 2023-06-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0017_remove_proof_proof_abr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofdesc',
            name='cercle',
        ),
        migrations.RemoveField(
            model_name='proofdesc',
            name='nom_memb',
        ),
    ]
