# Generated by Django 4.1.7 on 2023-06-14 17:34

import assisto.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0018_remove_proofdesc_cercle_remove_proofdesc_nom_memb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofdesc',
            name='pdf_name',
            field=models.FileField(null=True, upload_to='uploads/', validators=[assisto.validators.validate_file_extension]),
        ),
    ]
