# Generated by Django 4.1.7 on 2023-06-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0019_alter_proofdesc_pdf_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Societe',
        ),
    ]
