# Generated by Django 4.1.7 on 2023-06-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0020_delete_societe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_pdf', models.CharField(max_length=255)),
                ('nom_gerant', models.CharField(max_length=255)),
                ('rc_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assisto.users')),
            ],
        ),
    ]
