# Generated by Django 4.1.7 on 2023-06-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0021_societe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnc_pdf', models.CharField(max_length=255)),
                ('nom_president', models.CharField(max_length=255)),
                ('cnc_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assisto.users')),
            ],
        ),
    ]
