# Generated by Django 4.1.7 on 2023-06-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0022_cooperative2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cooperative',
        ),
    ]
