# Generated by Django 4.1.7 on 2023-06-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0023_delete_cooperative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnc_pdf', models.CharField(max_length=255)),
                ('nom_president', models.CharField(max_length=255)),
                ('cnc_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assisto.users', to_field='cnc_num')),
            ],
        ),
        migrations.AlterField(
            model_name='particulier',
            name='cin_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assisto.users', to_field='cin_num'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='rc_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assisto.users', to_field='rc_num'),
        ),
        migrations.DeleteModel(
            name='Cooperative2',
        ),
    ]
