# Generated by Django 4.1.7 on 2023-06-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0024_cooperative_alter_particulier_cin_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='cnc_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.users', to_field='cnc_num'),
        ),
        migrations.AlterField(
            model_name='particulier',
            name='cin_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.users', to_field='cin_num'),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.users'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='rc_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.users', to_field='rc_num'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.profession'),
        ),
        migrations.AlterField(
            model_name='users',
            name='proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.proof'),
        ),
    ]
