# Generated by Django 4.1.7 on 2023-06-15 20:32

import assisto.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0025_alter_cooperative_cnc_num_alter_particulier_cin_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='cnc_pdf',
            field=models.FileField(null=True, upload_to='uploads/', validators=[assisto.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='societe',
            name='rc_pdf',
            field=models.FileField(null=True, upload_to='uploads/', validators=[assisto.validators.validate_file_extension]),
        ),
    ]
