# Generated by Django 4.1.7 on 2023-06-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0026_alter_cooperative_cnc_pdf_alter_societe_rc_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Account types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_type', to='assisto.accounttype', verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
