# Generated by Django 4.1.7 on 2023-06-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0028_rename_user_acc_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofdesc',
            name='numreo',
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofdesc', to='assisto.users'),
        ),
    ]
