# Generated by Django 4.1.7 on 2023-06-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0029_remove_proofdesc_numreo_alter_proofdesc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofdesc',
            name='duree',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofdesc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofdesc_set', to='assisto.users'),
        ),
    ]
