# Generated by Django 4.1.7 on 2023-07-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0034_demandes_code_attestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandes',
            name='message',
        ),
    ]
