# Generated by Django 4.1.7 on 2023-07-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0035_remove_demandes_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc_user',
            name='acc_type',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
    ]
