# Generated by Django 4.1.7 on 2023-07-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0037_delete_phoneverification_alter_cooperative_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PP',
        ),
        migrations.AlterModelOptions(
            name='acc_user',
            options={'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='demandes',
            options={'verbose_name_plural': 'Demandes'},
        ),
        migrations.AlterModelOptions(
            name='proofdesc',
            options={'verbose_name_plural': 'Justifications'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Personnes'},
        ),
    ]
