# Generated by Django 4.1.7 on 2023-07-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0039_alter_demandes_demande_alter_proofdesc_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandes',
            old_name='demande',
            new_name='user_demande',
        ),
        migrations.RenameField(
            model_name='proofdesc',
            old_name='user',
            new_name='user_proof',
        ),
    ]
