# Generated by Django 4.1.7 on 2023-07-09 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0040_rename_demande_demandes_user_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='co_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.commune'),
        ),
        migrations.AddField(
            model_name='societe',
            name='so_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisto.commune'),
        ),
    ]
