# Generated by Django 4.1.7 on 2023-07-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0041_cooperative_co_commune_societe_so_commune'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='co_commune',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='so_commune',
        ),
    ]
