# Generated by Django 4.1.7 on 2023-07-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0042_remove_cooperative_co_commune_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='province',
        ),
    ]
