# Generated by Django 4.1.7 on 2023-07-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisto', '0044_particulier_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofdesc',
            name='province',
        ),
    ]
